import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const qs=[
["Apa yang dimaksud dengan LHO?",["Cerita lucu yang berisi kritik","Laporan berdasarkan hasil pengamatan yang faktual","Cerita pengalaman pribadi","Teks yang berisi pendapat penulis"],1,"LHO adalah laporan hasil observasi yang disusun berdasarkan fakta dari hasil pengamatan."],
["Kalimat “Kucing adalah hewan mamalia” termasuk kalimat...",["Deskripsi","Narasi","Definisi","Persuasi"],2,"Kalimat tersebut menjelaskan apa itu kucing, sehingga termasuk definisi."],
["Pertanyaan yang paling cocok untuk mengenali kalimat deskripsi adalah...",["Apa itu?","Siapa dia?","Seperti apa?","Mengapa terjadi?"],2,"Deskripsi menjelaskan ciri atau keadaan objek: seperti apa objek tersebut."],
["Urutan struktur LHO yang paling umum adalah...",["Krisis → Reaksi → Koda","Orientasi → Krisis → Reaksi","Pernyataan umum → Deskripsi bagian → Deskripsi manfaat","Abstraksi → Orientasi → Koda"],2,"Struktur LHO: pernyataan umum/klasifikasi, deskripsi bagian, lalu deskripsi manfaat jika diperlukan."],
["Anekdot biasanya memiliki unsur...",["Humor dan kritik/sindiran","Data statistik saja","Petunjuk penggunaan","Definisi ilmiah"],0,"Anekdot adalah cerita singkat yang lucu/menarik dan biasanya mengandung kritik atau sindiran."],
["Bagian anekdot yang berisi munculnya masalah atau kejadian lucu disebut...",["Abstraksi","Orientasi","Krisis","Koda"],2,"Krisis adalah bagian ketika masalah, keanehan, atau kejadian lucu mulai muncul."],
["Urutan struktur anekdot yang benar adalah...",["A-O-K-R-K","O-A-R-K-K","K-R-A-O-K","A-K-O-R-K"],0,"A-O-K-R-K = Abstraksi, Orientasi, Krisis, Reaksi, Koda."]
];
function App(){const[page,setPage]=useState("home"),[i,setI]=useState(0),[sel,setSel]=useState(null),[score,setScore]=useState(null);const q=qs[i];
function start(){setI(0);setSel(null);setScore(null);setPage("quiz")}
function next(){let answers=JSON.parse(sessionStorage.getItem("ans")||"[]");answers[i]=sel;sessionStorage.setItem("ans",JSON.stringify(answers));if(i===qs.length-1){let n=answers.filter((a,j)=>a===qs[j][3]).length;setScore(Math.round(n/qs.length*100));setPage("result")}else{setI(i+1);setSel(null)}}
return <><header><button className="brand" onClick={()=>setPage("home")}>🎓 Belajar AI</button><nav><button onClick={()=>setPage("home")}>Beranda</button><button onClick={start}>Latihan</button><button onClick={()=>setPage("materi")}>Materi</button></nav></header><main>
{page==="home"&&<section className="hero"><b className="badge">VERSI 1.0 • MVP</b><h1>Belajar lebih pintar,<br/><em>bukan lebih lama.</em></h1><p>Latihan soal, pembahasan, dan skor. Fondasinya siap dikembangkan menjadi tutor AI.</p><button className="primary" onClick={start}>Mulai Latihan →</button><div className="cards"><div>🧠<b>7 Soal</b><small>Latihan</small></div><div>📈<b>Instan</b><small>Nilai & pembahasan</small></div><div>🎯<b>Fokus</b><small>Review kesalahan</small></div></div></section>}
{page==="materi"&&<section className="content"><button className="back" onClick={()=>setPage("home")}>← Kembali</button><h2>Materi LHO & Anekdot</h2><article><h3>LHO</h3><p><b>Pengertian:</b> laporan berdasarkan hasil pengamatan yang faktual, objektif, dan sistematis.</p><p><b>Definisi:</b> menjawab “apa itu?”. Contoh: “Kucing adalah hewan mamalia.”</p><p><b>Deskripsi:</b> menjawab “seperti apa?”.</p><p><b>Struktur:</b> Pernyataan umum → Deskripsi bagian → Deskripsi manfaat.</p></article><article><h3>Anekdot</h3><p><b>Pengertian:</b> cerita singkat lucu/menarik yang biasanya mengandung kritik atau sindiran.</p><p><b>Struktur:</b> Abstraksi → Orientasi → Krisis → Reaksi → Koda.</p></article><button className="primary wide" onClick={start}>Uji Pemahaman →</button></section>}
{page==="quiz"&&<section className="quiz"><div className="quiztop">Soal {i+1} dari {qs.length}<span>{Math.round((i+1)/qs.length*100)}%</span></div><div className="bar"><i style={{width:`${(i+1)/qs.length*100}%`}}/></div><div className="box"><h2>{q[0]}</h2><div className="opts">{q[1].map((x,k)=><button className={`opt ${sel!==null&&k===q[3]?"correct":sel===k?"chosen":""} ${sel!==null&&sel===k&&k!==q[3]?"wrong":""}`} onClick={()=>sel===null&&setSel(k)} key={x}><b>{String.fromCharCode(65+k)}</b>{x}</button>)}</div>{sel!==null&&<p className="explain"><b>{sel===q[3]?"✓ Benar!":"✗ Belum tepat"}</b><br/>{q[4]}</p>}<button className="primary wide" disabled={sel===null} onClick={next}>{i===qs.length-1?"Lihat Hasil":"Soal Berikutnya →"}</button></div></section>}
{page==="result"&&<section className="result"><div>🔥</div><b className="badge">HASIL LATIHAN</b><h1>{score}%</h1><p>{score>=80?"Mantap. Lu udah cukup siap!":"Masih ada yang perlu diperkuat. Ulangi lagi biar makin siap."}</p><button className="primary" onClick={start}>Coba Lagi</button><button className="secondary" onClick={()=>setPage("materi")}>Pelajari Materi</button></section>}
</main></>}
createRoot(document.getElementById("root")).render(<App/>);